---
title: "R Intro2 Activity"
author: "Kat Wiles"
date: "October 14, 2015"
output: html_document
---

###1. Average recombination rate per motif type

Importing data
```{r import data, echo=TRUE}
mtfs <- read.delim("motif_recombrates.txt", header=TRUE) #read in motif recombination rates data
rpts <- read.delim("motif_repeats.txt", header=TRUE) #read in motif repeats data
```

need to connect motifs start from mtfs and rpts by chromosome and motif start
```{r merging motif repeats and motif recombination, echo=TRUE}
mtfs$pos <-paste(mtfs$chr, mtfs$motif_start, sep="-") 
rpts$pos <- paste(rpts$chr, rpts$motif_start, sep="-")
recm <-merge (mtfs, rpts, by.x="pos", by.y="pos")
```


Pulling out the average recombination rate
```{r avg recombo rate, echo=TRUE}
avg.recom <- aggregate(recm$recom, list(recm$name), mean) 
colnames(avg.recom) [2] <- "Average.recombrate" #renamed column 2 to average recombination rate
colnames(avg.recom) [1] <- "Motif.type" #renaming group1 to motif type
head(avg.recom)
```


###2. Do the distributions of recombination rate differ according to motif type?

Plotting data
```{r plot, echo=TRUE}
library(ggplot2)
ggplot(recm) + geom_density(aes(x=recom, fill=name), alpha=0.3) +xlab("Recombination Rate") +ylab("Density") + labs(fill="Motif Type")
```
#####The distribution of recombination rates seem to be pretty similar in both motif types.


###3. 



